const LOAD_OFFERS = `LOAD_OFFERS`;
const CHANGE_CITY = `CHANGE_CITY`;
const SORT_OPEN_TOGGLE = `SORT_OPEN_TOGGLE`;
const SORT_ACTIVE_OPTION_CHANGE = `SORT_ACTIVE_OPTION_CHANGE`;
const ACTIVATE_CARD = `ACTIVATE_CARD`;
const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;
const SAVE_USER = `SAVE_USER`;
const REMOVE_USER = `REMOVE_USER`;
const LOAD_COMMENTS = `LOAD_COMMENTS`;
const LOAD_FAVORITES = `LOAD_FAVORITE`;

export {
  LOAD_OFFERS,
  CHANGE_CITY,
  SORT_OPEN_TOGGLE,
  SORT_ACTIVE_OPTION_CHANGE,
  ACTIVATE_CARD,
  REQUIRED_AUTHORIZATION,
  SAVE_USER,
  REMOVE_USER,
  LOAD_COMMENTS,
  LOAD_FAVORITES,
};
