const LOAD_OFFERS = `LOAD_OFFERS`;
const CHANGE_CITY = `CHANGE_CITY`;
const GET_PROPERTIES = `GET_PROPERTIES`;
const SORT_OPEN_TOGGLE = `SORT_OPEN_TOGGLE`;
const SORT_ACTIVE_OPTION_CHANGE = `SORT_ACTIVE_OPTION_CHANGE`;
const SORT_PROPERTIES = `SORT_PROPERTIES`;
const ACTIVATE_CARD = `ACTIVATE_CARD`;
const REQUIRED_AUTHORIZATION = `REQUIRED_AUTHORIZATION`;

export {
  LOAD_OFFERS,
  CHANGE_CITY,
  GET_PROPERTIES,
  SORT_OPEN_TOGGLE,
  SORT_ACTIVE_OPTION_CHANGE,
  SORT_PROPERTIES,
  ACTIVATE_CARD,
  REQUIRED_AUTHORIZATION
};
